### ISSUE TITLE
Evaluate_algo.py looks for missing file ./algo_evaluation/data_evaluate/pdf_providers.csv

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [wellcometrust/policytool#171]
Trying to get the *Evaluating each component of the algorithm* instructions working from [README.md](https://github.com/wellcometrust/policytool/blob/master/README.md). After running `aws s3 cp --recursive s3://datalabs-data/policy_tool_tests algo_evaluation/data_evaluate/`:

```
$ python evaluate_algo.py
[2019-07-02 12:25:02,846]:INFO - Starting evaluations...
[2019-07-02 12:25:02,846]:INFO - Reading files...
[2019-07-02 12:25:02,846]:INFO - [+] Reading pdfs
Traceback (most recent call last):
  File "evaluate_algo.py", line 101, in <module>
    'csv'
  File "/home/matthew/Documents/wellcome/policytool/policytool/refparse/utils/file_manager.py", line
71, in get_file
    return self._get_from_local(file_prefix, file_name, file_type)
  File "/home/matthew/Documents/wellcome/policytool/policytool/refparse/utils/file_manager.py", line
86, in _get_from_local
    with open(file_path, 'rb') as file_content:
FileNotFoundError: [Errno 2] No such file or directory: './algo_evaluation/data_evaluate/pdf_providers.csv'
```

This is just an incorrect filename as the file `./algo_evaluation/data_evaluate/pdfs_providers.csv` does exist, but I can't seem to find where the reference to this file exists. See video for full explanation.

https://www.loom.com/share/cfbd9d104aa4490aa66bb60f98a295af

Additionally if I rename the above file so that it is found, I then run into the following

```
$ python evaluate_algo.py
[2019-07-02 12:45:57,149]:INFO - Starting evaluations...
[2019-07-02 12:45:57,149]:INFO - Reading files...
[2019-07-02 12:45:57,149]:INFO - [+] Reading pdfs
[2019-07-02 12:45:57,149]:INFO - Using ./algo_evaluation/data_evaluate/pdf_providers.csv file from local storage
[2019-07-02 12:45:57,157]:INFO - [+] Reading split_section_test_data.csv
[2019-07-02 12:45:57,157]:INFO - Using ./algo_evaluation/data_evaluate/split_section_test_data.csv file from local storage
[2019-07-02 12:45:57,161]:INFO - [+] Reading actual_reference_structures_sample.csv
[2019-07-02 12:45:57,161]:INFO - Using ./algo_evaluation/data_evaluate/actual_reference_structures_sample.csv file from local storage
[2019-07-02 12:45:57,166]:INFO - [+] Reading positive_and_negative_match_test_data.csv
Traceback (most recent call last):
  File "evaluate_algo.py", line 145, in <module>
    'csv'
  File "/home/matthew/Documents/wellcome/policytool/policytool/refparse/utils/file_manager.py", line 71, in get_file
    return self._get_from_local(file_prefix, file_name, file_type)
  File "/home/matthew/Documents/wellcome/policytool/policytool/refparse/utils/file_manager.py", line 86, in _get_from_local
    with open(file_path, 'rb') as file_content:
FileNotFoundError: [Errno 2] No such file or directory: './algo_evaluation/data_evaluate/positive_and_negative_match_test_data.csv'
```

**Comment by lizgzil** [comment]
@ivyleavedtoadflax hm, strange error, can you try running the code from the branch created in this PR https://github.com/wellcometrust/policytool/pull/163

**Comment by ivyleavedtoadflax** [comment]
Thanks @lizgzil - solved with your help!
